heap_unit: add missing limits import
This fixes the following build error:

    hub-labeling/src/heap_unit.cc: In function ‘void heap_test(int, int)’:
    hub-labeling/src/heap_unit.cc:31:21: error: ‘numeric_limits’ is not a member of ‘std’
       31 |     int last = std::numeric_limits<int>::min();
          |                     ^~~~~~~~~~~~~~
    hub-labeling/src/heap_unit.cc:31:36: error: expected primary-expression before ‘int’
       31 |     int last = std::numeric_limits<int>::min();
          |                                    ^~~
    make[3]: *** [CMakeFiles/unit.dir/build.make:76: CMakeFiles/unit.dir/src/heap_unit.cc.o] Error 1